import { NextResponse } from "next/server";
import { requireCurrentUser } from "@/lib/session";
import { assertPermission } from "@/lib/rbac";
import { handleApiError, AppError, NotFoundError } from "@/lib/errors";
import { ensureSandboxAgency, fatValidationService } from "@/server/services/fat-validation.service";

/**
 * GET /api/internal/fat/runs/[id]/export?scope=jobOrder|intelligence|complete
 *
 * Task 006.5 requirement 5 — three export buttons, one route. Returns
 * the same JSON `/runs/[id]` returns, filtered to the requested scope,
 * with a Content-Disposition header so the browser downloads it as a
 * file rather than navigating to it. No advertisement is generated by
 * any of the three scopes.
 */
export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await requireCurrentUser();
    assertPermission(user, "fat:access");

    const { id } = await params;
    const agencyId = await ensureSandboxAgency();
    const snapshot = await fatValidationService.getSnapshot(id, agencyId);
    if (!snapshot) throw new NotFoundError("FAT run");

    const scope = new URL(request.url).searchParams.get("scope") ?? "complete";

    let payload: unknown;
    let filenamePart: string;

    if (scope === "jobOrder") {
      payload = snapshot.jobOrder;
      filenamePart = "job-order";
    } else if (scope === "intelligence") {
      payload = {
        requirementIntelligence: snapshot.requirementIntelligence,
        jobOrderIntelligence: snapshot.jobOrderIntelligence,
        complianceIntelligence: snapshot.complianceIntelligence,
        campaignIntelligence: snapshot.campaignIntelligence,
        layoutIntelligence: snapshot.layoutIntelligence,
      };
      filenamePart = "intelligence";
    } else if (scope === "complete") {
      payload = snapshot;
      filenamePart = "complete";
    } else {
      throw new AppError(`Unknown export scope "${scope}".`, 400, "UNKNOWN_SCOPE");
    }

    return new NextResponse(JSON.stringify(payload, null, 2), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Content-Disposition": `attachment; filename="fat-${filenamePart}-${id}.json"`,
      },
    });
  } catch (error) {
    return handleApiError(error);
  }
}
